name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -coverprofile=coverage.out ./...
      - name: Lint
        run: golangci-lint run
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
