name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install GolangCI-Lint
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.2.2
      - name: Install gofumpt
        run: |
          go install mvdan.cc/gofumpt@v0.8.0

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck



      - name: Format
        run: make fmt
      - name: Vet
        run: make vet
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -coverprofile=coverage.out ./...
      - name: Lint
        run: make lint

      - name: Vulnerability Check
        run: make govulncheck

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
